default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: active_teaching_development

test:
  adapter: sqlite3
  pool: 5
  database: db/test.sqlite3

production:
  <<: *default