default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  reconnect: false
  database: active_teaching_development
  socket: /tmp/mysql.sock
  host: db

development:
  <<: *default

test:
  adapter: sqlite3
  pool: 5
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  url: <%= ENV['DATABASE_URL'] %>