default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: <%= Rails.application.credentials.db[:password] %>

development:
  <<: *default
  database: mysql_development
  host: localhost

test:
  adapter: sqlite3
  pool: 5
  database: db/test.sqlite3

production:
  database: Rails_Portfolio_production
  username: root
  password: <%= Rails.application.credentials.db[:password] %>
  host: <%= Rails.application.credentials.db[:hostname] %>